/** @type {import('tailwindcss').Config} */
const c = (name) => `rgb(var(--c-${name}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': c('on-background'),
        'surface-container': c('surface-container'),
        'inverse-on-surface': c('inverse-on-surface'),
        'surface-bright': c('surface-bright'),
        secondary: c('secondary'),
        'secondary-fixed': c('secondary-fixed'),
        'on-secondary': c('on-secondary'),
        'inverse-surface': c('inverse-surface'),
        'tertiary-fixed-dim': c('tertiary-fixed-dim'),
        error: c('error'),
        'on-error': c('on-error'),
        tertiary: c('tertiary'),
        'tertiary-container': c('tertiary-container'),
        'on-primary': c('on-primary'),
        'on-surface': c('on-surface'),
        'tertiary-fixed': c('tertiary-fixed'),
        'surface-container-lowest': c('surface-container-lowest'),
        surface: c('surface'),
        'inverse-primary': c('inverse-primary'),
        'secondary-fixed-dim': c('secondary-fixed-dim'),
        'outline-variant': c('outline-variant'),
        'primary-container': c('primary-container'),
        'primary-fixed-dim': c('primary-fixed-dim'),
        'on-primary-container': c('on-primary-container'),
        'on-secondary-container': c('on-secondary-container'),
        'on-error-container': c('on-error-container'),
        'on-primary-fixed-variant': c('on-primary-fixed-variant'),
        'secondary-container': c('secondary-container'),
        'on-surface-variant': c('on-surface-variant'),
        'on-tertiary': c('on-tertiary'),
        background: c('background'),
        'surface-variant': c('surface-variant'),
        'surface-container-highest': c('surface-container-highest'),
        'primary-fixed': c('primary-fixed'),
        'surface-dim': c('surface-dim'),
        'error-container': c('error-container'),
        primary: c('primary'),
        'on-secondary-fixed': c('on-secondary-fixed'),
        'on-tertiary-fixed-variant': c('on-tertiary-fixed-variant'),
        'on-primary-fixed': c('on-primary-fixed'),
        'surface-container-low': c('surface-container-low'),
        'surface-tint': c('surface-tint'),
        outline: c('outline'),
        'on-tertiary-container': c('on-tertiary-container'),
        'surface-container-high': c('surface-container-high'),
        'on-secondary-fixed-variant': c('on-secondary-fixed-variant'),
        'on-tertiary-fixed': c('on-tertiary-fixed'),
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '32px',
        'stack-md': '16px',
        base: '4px',
        gutter: '16px',
        'stack-sm': '8px',
        'container-padding': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        h3: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        h1: ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'scale-in': {
          from: { opacity: '0', transform: 'translateY(8px) scale(0.98)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'scale-in': 'scale-in 0.18s ease-out',
        'slide-in-right': 'slide-in-right 0.25s ease-out',
      },
    },
  },
  plugins: [],
};
