import { useEffect, useRef, useState } from 'react';
import { Button, Field, Icon, Input, Modal, Select, Textarea } from '@/components/ui';
import { useToast } from '@/providers/ToastProvider';
import {
  useCreateProduct,
  useUpdateProduct,
  useUploadProductImage,
} from '@/hooks/useProducts';
import { useUploadImage } from '@/hooks/useUploads';
import { extractMessage } from '@/lib/api';
import { imageSrc, num } from '@/lib/utils';
import type { Category, Product } from '@/types';

interface FormState {
  sku: string;
  name: string;
  description: string;
  categoryId: string;
  sellingPrice: string;
  buyingPrice: string;
  baseUnit: string;
  bulkUnit: string;
  unitSize: string;
  bulkSellingPrice: string;
  minStockLevel: string;
  status: 'ACTIVE' | 'INACTIVE';
}

const EMPTY: FormState = {
  sku: '',
  name: '',
  description: '',
  categoryId: '',
  sellingPrice: '',
  buyingPrice: '',
  baseUnit: 'pcs',
  bulkUnit: '',
  unitSize: '',
  bulkSellingPrice: '',
  minStockLevel: '0',
  status: 'ACTIVE',
};

export function ProductFormModal({
  open,
  onClose,
  product,
  categories,
}: {
  open: boolean;
  onClose: () => void;
  product: Product | null;
  categories: Category[];
}) {
  const toast = useToast();
  const create = useCreateProduct();
  const update = useUpdateProduct();
  const uploadNew = useUploadImage();
  const uploadExisting = useUploadProductImage();
  const fileRef = useRef<HTMLInputElement>(null);

  const [form, setForm] = useState<FormState>(EMPTY);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);

  const isEdit = !!product;
  const saving = create.isPending || update.isPending || uploadNew.isPending || uploadExisting.isPending;

  useEffect(() => {
    if (!open) return;
    setErrors({});
    setFile(null);
    if (product) {
      setForm({
        sku: product.sku,
        name: product.name,
        description: product.description ?? '',
        categoryId: product.categoryId ?? '',
        sellingPrice: num(product.sellingPrice).toString(),
        buyingPrice: num(product.buyingPrice).toString(),
        baseUnit: product.baseUnit || 'pcs',
        bulkUnit: product.bulkUnit ?? '',
        unitSize: product.bulkUnit ? product.unitSize.toString() : '',
        bulkSellingPrice: product.bulkSellingPrice ? num(product.bulkSellingPrice).toString() : '',
        minStockLevel: product.minStockLevel.toString(),
        status: product.status,
      });
      setPreview(imageSrc(product.imageUrl));
    } else {
      setForm(EMPTY);
      setPreview(null);
    }
  }, [open, product]);

  const set = (k: keyof FormState, v: string) => setForm((f) => ({ ...f, [k]: v }));

  const onPickFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setFile(f);
    setPreview(URL.createObjectURL(f));
  };

  const validate = (): boolean => {
    const errs: Record<string, string> = {};
    // SKU is generated by the backend, so it is no longer collected here.
    if (!form.name.trim()) errs.name = 'Name is required';
    if (form.sellingPrice === '' || num(form.sellingPrice) < 0) errs.sellingPrice = 'Enter a valid price';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validate()) return;

    try {
      // Note: SKU is intentionally never sent — the backend generates it on
      // create and treats it as immutable on update.
      const bulkUnit = form.bulkUnit.trim();
      const base = {
        name: form.name.trim(),
        description: form.description.trim() || undefined,
        categoryId: form.categoryId || undefined,
        sellingPrice: num(form.sellingPrice),
        buyingPrice: form.buyingPrice === '' ? undefined : num(form.buyingPrice),
        baseUnit: form.baseUnit.trim() || 'pcs',
        // Always send the bulk unit (empty string disables/clears pack selling).
        bulkUnit,
        unitSize: bulkUnit ? Math.max(1, parseInt(form.unitSize || '1', 10)) : undefined,
        bulkSellingPrice: bulkUnit && form.bulkSellingPrice !== '' ? num(form.bulkSellingPrice) : undefined,
        minStockLevel: form.minStockLevel === '' ? undefined : parseInt(form.minStockLevel, 10),
        status: form.status,
      };

      if (isEdit) {
        await update.mutateAsync({ id: product!.id, input: base });
        if (file) await uploadExisting.mutateAsync({ id: product!.id, file });
        toast.success('Product updated', `${base.name} saved successfully.`);
      } else {
        let imageUrl: string | undefined;
        if (file) imageUrl = await uploadNew.mutateAsync(file);
        await create.mutateAsync({ ...base, imageUrl });
        toast.success('Product created', `${base.name} added to the catalog.`);
      }
      onClose();
    } catch (err) {
      toast.error('Save failed', extractMessage(err));
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      size="lg"
      title={isEdit ? 'Edit Product' : 'Add Product'}
      subtitle={isEdit ? product?.sku : 'Create a new catalog item'}
      footer={
        <>
          <Button variant="outline" onClick={onClose} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={submit} loading={saving} icon="check">
            {isEdit ? 'Save changes' : 'Create product'}
          </Button>
        </>
      }
    >
      <form onSubmit={submit} className="space-y-5">
        <div className="flex gap-5">
          {/* Image */}
          <div className="shrink-0">
            <button
              type="button"
              onClick={() => fileRef.current?.click()}
              className="group relative flex h-28 w-28 items-center justify-center overflow-hidden rounded-xl border-2 border-dashed border-outline-variant bg-surface-container-low transition-colors hover:border-secondary"
            >
              {preview ? (
                <img src={preview} alt="Preview" className="h-full w-full object-cover" />
              ) : (
                <div className="flex flex-col items-center text-on-surface-variant">
                  <Icon name="add_photo_alternate" size={28} />
                  <span className="mt-1 text-[11px]">Add photo</span>
                </div>
              )}
              <span className="absolute inset-x-0 bottom-0 hidden bg-on-background/60 py-1 text-center text-[10px] font-semibold text-white group-hover:block">
                Change
              </span>
            </button>
            <input ref={fileRef} type="file" accept="image/*" hidden onChange={onPickFile} />
          </div>

          <div className="grid flex-1 grid-cols-2 gap-4">
            <Field label="Name" required error={errors.name} className="col-span-2">
              <Input value={form.name} onChange={(e) => set('name', e.target.value)} invalid={!!errors.name} placeholder="A4 Paper (Ream)" />
            </Field>
            {isEdit && (
              <Field label="SKU" hint="Auto-generated · not editable">
                <Input value={form.sku} disabled readOnly />
              </Field>
            )}
            <Field label="Category" className={isEdit ? undefined : 'col-span-2'}>
              <Select value={form.categoryId} onChange={(e) => set('categoryId', e.target.value)}>
                <option value="">Uncategorized</option>
                {categories.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </Select>
            </Field>
          </div>
        </div>

        <Field label="Description">
          <Textarea
            value={form.description}
            onChange={(e) => set('description', e.target.value)}
            placeholder="Optional product description…"
          />
        </Field>

        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          <Field label="Selling Price" required error={errors.sellingPrice}>
            <Input
              type="number"
              min="0"
              step="0.01"
              value={form.sellingPrice}
              onChange={(e) => set('sellingPrice', e.target.value)}
              invalid={!!errors.sellingPrice}
            />
          </Field>
          <Field label="Buying Price">
            <Input
              type="number"
              min="0"
              step="0.01"
              value={form.buyingPrice}
              onChange={(e) => set('buyingPrice', e.target.value)}
            />
          </Field>
          <Field label="Min Stock">
            <Input
              type="number"
              min="0"
              value={form.minStockLevel}
              onChange={(e) => set('minStockLevel', e.target.value)}
            />
          </Field>
          <Field label="Status">
            <Select value={form.status} onChange={(e) => set('status', e.target.value)}>
              <option value="ACTIVE">Active</option>
              <option value="INACTIVE">Inactive</option>
            </Select>
          </Field>
        </div>

        {/* Units of measure */}
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-4">
          <p className="text-label-caps uppercase tracking-wide text-on-surface-variant">Units of measure</p>
          <p className="mt-0.5 text-[12px] text-on-surface-variant">
            Stock is always counted in the base unit. Add a pack unit to also sell/buy in bulk (e.g. a Box of 12 pcs).
          </p>
          <div className="mt-3 grid grid-cols-2 gap-4 sm:grid-cols-4">
            <Field label="Base unit" hint="e.g. pcs">
              <Input value={form.baseUnit} onChange={(e) => set('baseUnit', e.target.value)} placeholder="pcs" />
            </Field>
            <Field label="Pack unit" hint="optional">
              <Input value={form.bulkUnit} onChange={(e) => set('bulkUnit', e.target.value)} placeholder="Box" />
            </Field>
            <Field label="Pcs per pack">
              <Input
                type="number"
                min="1"
                value={form.unitSize}
                onChange={(e) => set('unitSize', e.target.value)}
                placeholder="12"
                disabled={!form.bulkUnit.trim()}
              />
            </Field>
            <Field label="Pack price" hint="blank = pcs×size">
              <Input
                type="number"
                min="0"
                step="0.01"
                value={form.bulkSellingPrice}
                onChange={(e) => set('bulkSellingPrice', e.target.value)}
                disabled={!form.bulkUnit.trim()}
              />
            </Field>
          </div>
        </div>

        {isEdit && (
          <p className="flex items-center gap-1.5 text-[12px] text-on-surface-variant">
            <Icon name="info" size={16} /> Stock is adjusted via Purchases and Inventory, not edited here.
          </p>
        )}
      </form>
    </Modal>
  );
}
