import { BadRequestException, Injectable } from '@nestjs/common';
import { existsSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';

export interface StartupStatus {
  /** Whether automatic startup can be managed on this host (Windows only). */
  supported: boolean;
  /** Whether automatic startup is currently registered. */
  enabled: boolean;
  platform: string;
  /** Full path of the launcher we manage (null when unsupported). */
  launcherPath: string | null;
  /** Whether a production build exists so `npm run serve` can actually start. */
  productionReady: boolean;
  /** URL the launcher opens. */
  url: string;
}

const APP_URL = 'http://localhost:3000';

/**
 * Manages whether the app launches automatically when Windows starts. Uses the
 * per-user Startup folder (no admin rights needed): a small .cmd there runs the
 * production server and opens the browser on login. A true auto-restarting
 * Windows Service needs elevation and is set up separately.
 */
@Injectable()
export class SystemService {
  private readonly projectRoot = process.cwd();

  private startupDir(): string | null {
    const appData = process.env.APPDATA;
    if (process.platform !== 'win32' || !appData) return null;
    return join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
  }

  private launcherPath(): string | null {
    const dir = this.startupDir();
    return dir ? join(dir, 'KJ-Stationery.cmd') : null;
  }

  private productionReady(): boolean {
    return (
      existsSync(join(this.projectRoot, 'dist', 'src', 'main.js')) &&
      existsSync(join(this.projectRoot, 'frontend', 'dist', 'index.html'))
    );
  }

  status(): StartupStatus {
    const launcherPath = this.launcherPath();
    return {
      supported: !!launcherPath,
      enabled: !!launcherPath && existsSync(launcherPath),
      platform: process.platform,
      launcherPath,
      productionReady: this.productionReady(),
      url: APP_URL,
    };
  }

  setEnabled(enabled: boolean): StartupStatus {
    const launcherPath = this.launcherPath();
    if (!launcherPath) {
      throw new BadRequestException('Automatic startup is only supported on Windows.');
    }
    if (enabled) {
      writeFileSync(launcherPath, this.launcherScript(), 'utf8');
    } else if (existsSync(launcherPath)) {
      rmSync(launcherPath, { force: true });
    }
    return this.status();
  }

  /** Contents of the Startup-folder launcher. Deleting it disables startup. */
  private launcherScript(): string {
    return [
      '@echo off',
      'REM Auto-generated by KJ Stationery (Settings > System). Deleting this file disables startup.',
      `cd /d "${this.projectRoot}"`,
      'REM Start the server minimized in the background.',
      'start "KJ Stationery Server" /min cmd /c "npm run serve"',
      'REM Wait for it to come up, then open the app in the default browser.',
      'timeout /t 6 >nul',
      `start "" "${APP_URL}"`,
      '',
    ].join('\r\n');
  }
}
