import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, unwrap } from '@/lib/api';
import { qk } from './keys';
import type { LowStockRow, Paginated, Product, ProductStatus } from '@/types';

export interface ProductFilters {
  page?: number;
  limit?: number;
  search?: string;
  status?: ProductStatus;
  categoryId?: string;
  lowStock?: boolean;
}

function clean(params: Record<string, unknown>) {
  return Object.fromEntries(
    Object.entries(params).filter(([, v]) => v !== undefined && v !== '' && v !== null),
  );
}

export function useProducts(filters: ProductFilters) {
  return useQuery({
    queryKey: qk.products(filters),
    queryFn: async () => {
      const res = await api.get<Paginated<Product>>('/products', { params: clean({ ...filters }) });
      return res.data;
    },
  });
}

export function useProduct(id: string | undefined) {
  return useQuery({
    queryKey: qk.product(id ?? ''),
    enabled: !!id,
    queryFn: () => unwrap<Product>(api.get(`/products/${id}`)),
  });
}

export function useLowStockProducts() {
  return useQuery({
    queryKey: qk.lowStock(),
    queryFn: () => unwrap<LowStockRow[]>(api.get('/products/low-stock')),
    staleTime: 60_000,
  });
}

export interface ProductInput {
  /** Optional — generated by the backend on create, immutable on update. */
  sku?: string;
  name: string;
  description?: string;
  imageUrl?: string;
  categoryId?: string;
  sellingPrice: number;
  buyingPrice?: number;
  minStockLevel?: number;
  status?: ProductStatus;
}

export function useCreateProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (input: ProductInput) => unwrap<Product>(api.post('/products', input)),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['products'] }),
  });
}

export function useUpdateProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, input }: { id: string; input: Partial<ProductInput> }) =>
      unwrap<Product>(api.patch(`/products/${id}`, input)),
    onSuccess: (_d, { id }) => {
      qc.invalidateQueries({ queryKey: ['products'] });
      qc.invalidateQueries({ queryKey: qk.product(id) });
    },
  });
}

export function useDeleteProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => api.delete(`/products/${id}`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['products'] }),
  });
}

/** Permanently deletes a product (only allowed when it has no history). */
export function useRemoveProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => api.delete(`/products/${id}/permanent`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['products'] }),
  });
}

export function useUploadProductImage() {
  return useMutation({
    mutationFn: async ({ id, file }: { id: string; file: File }) => {
      const form = new FormData();
      form.append('file', file);
      const res = await api.post(`/products/${id}/image`, form, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      return (res.data?.data ?? res.data) as Product;
    },
  });
}
